# Tensors

In [1]:
# Importing TF and checking the version
import tensorflow as tf
print(tf.__version__)

2.10.0


In [2]:
# Dataset
X = tf.range(-100, 100, 4)
X

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([-100,  -96,  -92,  -88,  -84,  -80,  -76,  -72,  -68,  -64,  -60,
        -56,  -52,  -48,  -44,  -40,  -36,  -32,  -28,  -24,  -20,  -16,
        -12,   -8,   -4,    0,    4,    8,   12,   16,   20,   24,   28,
         32,   36,   40,   44,   48,   52,   56,   60,   64,   68,   72,
         76,   80,   84,   88,   92,   96])>

In [3]:
# Labels
y = X + 10
y

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([-90, -86, -82, -78, -74, -70, -66, -62, -58, -54, -50, -46, -42,
       -38, -34, -30, -26, -22, -18, -14, -10,  -6,  -2,   2,   6,  10,
        14,  18,  22,  26,  30,  34,  38,  42,  46,  50,  54,  58,  62,
        66,  70,  74,  78,  82,  86,  90,  94,  98, 102, 106])>

In [4]:
# Creating train / test datasets
X_train = X[:40]
y_train = y[:40]

X_test = X[40:]
y_test = y[40:]

In [5]:
# Creating NN
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=[1])
])

model.compile(loss=tf.keras.losses.mae,
    optimizer=tf.keras.optimizers.SGD(),
    metrics=["mae"]
)

In [7]:
model.fit(X_train, y_train, epochs=100)

Epoch 1/100
2/2 [==============================] - 0s 3ms/step - loss: 9.1947 - mae: 9.1947
Epoch 2/100
2/2 [==============================] - 0s 7ms/step - loss: 15.8968 - mae: 15.8968
Epoch 3/100
2/2 [==============================] - 0s 0s/step - loss: 8.5529 - mae: 8.5529
Epoch 4/100
2/2 [==============================] - 0s 7ms/step - loss: 11.0424 - mae: 11.0424
Epoch 5/100
2/2 [==============================] - 0s 7ms/step - loss: 9.6131 - mae: 9.6131
Epoch 6/100
2/2 [==============================] - 0s 0s/step - loss: 9.5945 - mae: 9.5945
Epoch 7/100
2/2 [==============================] - 0s 10ms/step - loss: 10.8553 - mae: 10.8553
Epoch 8/100
2/2 [==============================] - 0s 8ms/step - loss: 15.4594 - mae: 15.4594
Epoch 9/100
2/2 [==============================] - 0s 0s/step - loss: 8.2549 - mae: 8.2549
Epoch 10/100
2/2 [==============================] - 0s 0s/step - loss: 11.5914 - mae: 11.5914
Epoch 11/100
2/2 [==============================] - 0s 0s/step - loss: 1