# Tensors

In [2]:
# Importing TF and checking the version
import tensorflow as tf
print(tf.__version__)

2.10.0


In [3]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of tensor dimensions
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([1, 2, 3])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [6]:
# Check the number of vector dimensions
vector.ndim

1

In [7]:
# Create a matrix
matrix = tf.constant([[1, 2], [3, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [8]:
# Check the number of matrix dimensions
matrix.ndim

2

In [9]:
# Create one more matrix
another_matrix = tf.constant([[1., 2.],
                            [3., 4.],
                            [5., 6.]], dtype=tf.float16)
another_matrix                            

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [10]:
# Using tf.Variable
tensor_var = tf.Variable([1, 2, 3])
tensor_fix = tf.constant([1, 2, 3])
tensor_var, tensor_fix

(<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>)

In [11]:
# Change the value of tensor
tensor_var[0].assign(5)
tensor_var

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([5, 2, 3])>

In [12]:
# Change the value of tensor
tensor_fix[0].assign(5)

# THIS DOESN'T WORK AS TENSOR IS CREATED WITH A CONSTANT FUNCTION

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [13]:
# Create random tensor
tensor_random1 = tf.random.Generator.from_seed(42)
tensor_random1 = tensor_random1.normal(shape=(3, 2))
tensor_random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [15]:
# Shuffle tensor values across first dimension
tensor_random1_shuffled = tf.random.shuffle(tensor_random1)
tensor_random1_shuffled

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [-0.7565803 , -0.06854702]], dtype=float32)>

In [16]:
tensor_ones = tf.ones([3, 2])
tensor_ones

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>