# Tensors

In [4]:
# Importing TF and checking the version
import tensorflow as tf
print(tf.__version__)

2.10.0


In [5]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# Check the number of tensor dimensions
scalar.ndim

0

In [7]:
# Create a vector
vector = tf.constant([1, 2, 3])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [8]:
# Check the number of vector dimensions
vector.ndim

1

In [9]:
# Create a matrix
matrix = tf.constant([[1, 2], [3, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [11]:
# Check the number of matrix dimensions
matrix.ndim

2

In [13]:
# Create one more matrix
another_matrix = tf.constant([[1., 2.],
                            [3., 4.],
                            [5., 6.]], dtype=tf.float16)
another_matrix                            

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [14]:
# Using tf.Variable
tensor_var = tf.Variable([1, 2, 3])
tensor_fix = tf.constant([1, 2, 3])
tensor_var, tensor_fix

(<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>)

In [15]:
tensor_var[0].assign(5)
tensor_var

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([5, 2, 3])>