# Tensors

In [1]:
import numpy as np
# Importing TF and checking the version
import tensorflow as tf
print(tf.__version__)

2.10.0


In [2]:
A = tf.constant([-1, -2])
A

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -2])>

In [3]:
# Getting absolute values
tf.abs(A)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [4]:
# Getting minimum value
tf.reduce_min(A)

<tf.Tensor: shape=(), dtype=int32, numpy=-2>

In [5]:
# Getting maximum value
tf.reduce_max(A)

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

In [6]:
# Getting mean value
tf.reduce_mean(A)

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

In [7]:
B = tf.constant([1, 2])
B

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [8]:
# Getting standard variance
# ------------ WILL NOT WORK BECAUSE OF DEFAULT TYPE
tf.math.reduce_variance(B)

TypeError: Input must be either real or complex. Received integer type <dtype: 'int32'>.

In [9]:
# Getting standard variance
# ------------ SHOUL WORK AFTER FIXING DATA TYPE
tf.math.reduce_variance(tf.cast(B, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=0.25>

In [10]:
# New tensor for the positional mix / max
tf.random.set_seed(42)
C = tf.random.uniform(shape=[50])
C

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [11]:
# Finding the positional maximum
tf.argmax(C)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [12]:
# Get the value from the index of argmax
C[tf.argmax(C)].numpy()

0.9671384

In [13]:
# Double-check the max
tf.reduce_max(C)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [14]:
# New tensor for squeezing (removal of 1-dimensions)
tf.random.set_seed(42)
D = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 50))
D

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [15]:
D.shape

TensorShape([1, 1, 1, 50])

In [16]:
D_squeezed = tf.squeeze(D)
D_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [17]:
D_squeezed.shape

TensorShape([50])

In [18]:
# Tesying one-hot encoder

my_list = [0, 1, 2]
tf.one_hot(my_list, depth=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [19]:
# One-hot encoder with custom values
tf.one_hot(my_list, depth=3, on_value="Yes", off_value="No")

<tf.Tensor: shape=(3, 3), dtype=string, numpy=
array([[b'Yes', b'No', b'No'],
       [b'No', b'Yes', b'No'],
       [b'No', b'No', b'Yes']], dtype=object)>

# Additional Math operations

In [20]:
# New tensor
E = tf.range(1, 10)
E

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [22]:
# Square it
tf.square(E)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>