# Tensors

In [1]:
import numpy as np
# Importing TF and checking the version
import tensorflow as tf
print(tf.__version__)

2.10.0


In [2]:
A = tf.constant([-1, -2])
A

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -2])>

In [3]:
# Getting absolute values
tf.abs(A)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [4]:
# Getting minimum value
tf.reduce_min(A)

<tf.Tensor: shape=(), dtype=int32, numpy=-2>

In [5]:
# Getting maximum value
tf.reduce_max(A)

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

In [6]:
# Getting mean value
tf.reduce_mean(A)

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

In [7]:
B = tf.constant([1, 2])
B

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [8]:
# Getting standard variance
# ------------ WILL NOT WORK BECAUSE OF DEFAULT TYPE
tf.math.reduce_variance(B)

TypeError: Input must be either real or complex. Received integer type <dtype: 'int32'>.

In [9]:
# Getting standard variance
# ------------ SHOUL WORK AFTER FIXING DATA TYPE
tf.math.reduce_variance(tf.cast(B, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=0.25>